<template>
    <div class="mt-4 text-left">
        <span
            class="px-4 pt-1 pb-3 text-sm leading-normal font-normal text-[#49749c]"
        >
            The question was generated by AI
        </span>
    </div>
</template>
